{{- if not .Values.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "satplan.secretName" . }}
  labels:
    {{- include "satplan.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.jwt.secretKey }}: {{ .Values.jwt.secret | quote }}
{{- end }}
