name = 'calm-wave-3f68'
compatibility_date = "2024-04-01"
type = "javascript"

[functions]
directory = "./functions"

[assets]
directory = "./static"

[[d1_databases]]
binding = "SATPLAN_D1"
database_name = "satplan"
database_id = "6a636ab2-2639-441c-8498-9ede26a394c2"